GRANT USAGE ON SCHEMA kb TO kb_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA kb TO kb_app;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA kb TO kb_app;
REVOKE ALL ON FUNCTION kb.ensure_vector_index(text,int) FROM PUBLIC;
ALTER TABLE kb.schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.schema_migrations FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.schema_migrations TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.workspaces FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.workspaces TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.users FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.users TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.members FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.members TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.scopes ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.scopes FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.scopes TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.documents FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.documents TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.document_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.document_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.document_versions TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.relations FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.relations TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.sources FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.sources TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.chunks FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.chunks TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.embeddings FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.embeddings TO kb_owner USING(true) WITH CHECK(true);
ALTER TABLE kb.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE kb.events FORCE ROW LEVEL SECURITY;
CREATE POLICY admin ON kb.events TO kb_owner USING(true) WITH CHECK(true);
CREATE POLICY own_identity ON kb.users FOR SELECT TO kb_app USING(db_role=current_user);
CREATE POLICY own_membership ON kb.members FOR SELECT TO kb_app USING(user_id=kb.current_user_id());
CREATE POLICY workspace_read ON kb.workspaces FOR SELECT TO kb_app USING(kb.workspace_role(id) IS NOT NULL);
CREATE POLICY read ON kb.scopes FOR SELECT TO kb_app USING(kb.workspace_role(workspace_id) IS NOT NULL AND (kind<>'personal' OR owner_user_id=kb.current_user_id()));
CREATE POLICY ins ON kb.scopes FOR INSERT TO kb_app WITH CHECK(kb.workspace_role(workspace_id) IN ('owner','editor') AND (kind<>'personal' OR owner_user_id=kb.current_user_id()));
CREATE POLICY upd ON kb.scopes FOR UPDATE TO kb_app USING(kb.workspace_role(workspace_id) IN ('owner','editor') AND (kind<>'personal' OR owner_user_id=kb.current_user_id())) WITH CHECK(kb.workspace_role(workspace_id) IN ('owner','editor') AND (kind<>'personal' OR owner_user_id=kb.current_user_id()));
CREATE POLICY del ON kb.scopes FOR DELETE TO kb_app USING(kb.workspace_role(workspace_id)='owner' AND (kind<>'personal' OR owner_user_id=kb.current_user_id()));
CREATE POLICY read ON kb.documents FOR SELECT TO kb_app USING(kb.scope_access(scope_id) AND (kind<>'inbox' OR author_id=kb.current_user_id() OR EXISTS(SELECT 1 FROM kb.scopes WHERE id=scope_id AND kb.workspace_role(workspace_id)='owner')));
CREATE POLICY ins ON kb.documents FOR INSERT TO kb_app WITH CHECK(kb.scope_access(scope_id,ARRAY['owner','editor']) AND (kind<>'inbox' OR author_id=kb.current_user_id() OR EXISTS(SELECT 1 FROM kb.scopes WHERE id=scope_id AND kb.workspace_role(workspace_id)='owner')));
CREATE POLICY upd ON kb.documents FOR UPDATE TO kb_app USING(kb.scope_access(scope_id,ARRAY['owner','editor']) AND (kind<>'inbox' OR author_id=kb.current_user_id() OR EXISTS(SELECT 1 FROM kb.scopes WHERE id=scope_id AND kb.workspace_role(workspace_id)='owner'))) WITH CHECK(kb.scope_access(scope_id,ARRAY['owner','editor']) AND (kind<>'inbox' OR author_id=kb.current_user_id() OR EXISTS(SELECT 1 FROM kb.scopes WHERE id=scope_id AND kb.workspace_role(workspace_id)='owner')));
CREATE POLICY del ON kb.documents FOR DELETE TO kb_app USING(kb.scope_access(scope_id,ARRAY['owner']) AND (kind<>'inbox' OR author_id=kb.current_user_id() OR EXISTS(SELECT 1 FROM kb.scopes WHERE id=scope_id AND kb.workspace_role(workspace_id)='owner')));
CREATE POLICY read ON kb.document_versions FOR SELECT TO kb_app USING(kb.doc_access(doc_id));
CREATE POLICY ins ON kb.document_versions FOR INSERT TO kb_app WITH CHECK(kb.doc_access(doc_id,ARRAY['owner','editor']));
CREATE POLICY upd ON kb.document_versions FOR UPDATE TO kb_app USING(kb.doc_access(doc_id,ARRAY['owner','editor'])) WITH CHECK(kb.doc_access(doc_id,ARRAY['owner','editor']));
CREATE POLICY del ON kb.document_versions FOR DELETE TO kb_app USING(kb.doc_access(doc_id,ARRAY['owner']));
CREATE POLICY read ON kb.sources FOR SELECT TO kb_app USING(kb.doc_access(doc_id));
CREATE POLICY ins ON kb.sources FOR INSERT TO kb_app WITH CHECK(kb.doc_access(doc_id,ARRAY['owner','editor']));
CREATE POLICY upd ON kb.sources FOR UPDATE TO kb_app USING(kb.doc_access(doc_id,ARRAY['owner','editor'])) WITH CHECK(kb.doc_access(doc_id,ARRAY['owner','editor']));
CREATE POLICY del ON kb.sources FOR DELETE TO kb_app USING(kb.doc_access(doc_id,ARRAY['owner']));
CREATE POLICY read ON kb.chunks FOR SELECT TO kb_app USING(kb.doc_access(doc_id));
CREATE POLICY ins ON kb.chunks FOR INSERT TO kb_app WITH CHECK(kb.doc_access(doc_id,ARRAY['owner','editor']));
CREATE POLICY upd ON kb.chunks FOR UPDATE TO kb_app USING(kb.doc_access(doc_id,ARRAY['owner','editor'])) WITH CHECK(kb.doc_access(doc_id,ARRAY['owner','editor']));
CREATE POLICY del ON kb.chunks FOR DELETE TO kb_app USING(kb.doc_access(doc_id,ARRAY['owner']));
CREATE POLICY read ON kb.relations FOR SELECT TO kb_app USING(kb.doc_access(src_id) AND kb.doc_access(dst_id));
CREATE POLICY ins ON kb.relations FOR INSERT TO kb_app WITH CHECK(kb.doc_access(src_id,ARRAY['owner','editor']) AND kb.doc_access(dst_id,ARRAY['owner','editor']));
CREATE POLICY upd ON kb.relations FOR UPDATE TO kb_app USING(kb.doc_access(src_id,ARRAY['owner','editor']) AND kb.doc_access(dst_id,ARRAY['owner','editor'])) WITH CHECK(kb.doc_access(src_id,ARRAY['owner','editor']) AND kb.doc_access(dst_id,ARRAY['owner','editor']));
CREATE POLICY del ON kb.relations FOR DELETE TO kb_app USING(kb.doc_access(src_id,ARRAY['owner']) AND kb.doc_access(dst_id,ARRAY['owner']));
CREATE POLICY read ON kb.embeddings FOR SELECT TO kb_app USING(EXISTS(SELECT 1 FROM kb.chunks WHERE id=chunk_id AND kb.doc_access(doc_id,ARRAY['owner','editor','viewer'])));
CREATE POLICY ins ON kb.embeddings FOR INSERT TO kb_app WITH CHECK(EXISTS(SELECT 1 FROM kb.chunks WHERE id=chunk_id AND kb.doc_access(doc_id,ARRAY['owner','editor'])));
CREATE POLICY upd ON kb.embeddings FOR UPDATE TO kb_app USING(EXISTS(SELECT 1 FROM kb.chunks WHERE id=chunk_id AND kb.doc_access(doc_id,ARRAY['owner','editor']))) WITH CHECK(EXISTS(SELECT 1 FROM kb.chunks WHERE id=chunk_id AND kb.doc_access(doc_id,ARRAY['owner','editor'])));
CREATE POLICY del ON kb.embeddings FOR DELETE TO kb_app USING(EXISTS(SELECT 1 FROM kb.chunks WHERE id=chunk_id AND kb.doc_access(doc_id,ARRAY['owner'])));
CREATE POLICY own_events ON kb.events FOR SELECT TO kb_app USING(user_id=kb.current_user_id());
CREATE POLICY log_events ON kb.events FOR INSERT TO kb_app WITH CHECK(user_id=kb.current_user_id() AND (doc_id IS NULL OR kb.doc_access(doc_id)));
